# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: HIL_group
  joint_model_group_pose: tourner1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_chassis_virtual_joint
    - chassis_bras1
    - bras2_moteur
    - moteur_poussoirCentralPince
    - poussoirCentralPince_miniBrasPinceExt1
    - miniBrasPinceExt2_boutDePince1
    - poussoirCentralPince_miniBrasPinceExt2
    - miniBrasPinceExt2_boutDePince1
    - poussoirCentralPince_miniBrasPinceExt3
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceExt4
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceInt1
    - poussoirCentralPince_miniBrasPinceExt4
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceInt2
    - poussoirCentralPince_miniBrasPinceExt1
    - miniBrasPinceExt2_boutDePince1
    - chassis_bras2
    - bras2_moteur
    - moteur_poussoirCentralPince
    - poussoirCentralPince_miniBrasPinceExt1
    - miniBrasPinceExt2_boutDePince1
    - poussoirCentralPince_miniBrasPinceExt2
    - miniBrasPinceExt2_boutDePince1
    - poussoirCentralPince_miniBrasPinceExt3
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceExt4
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceInt1
    - poussoirCentralPince_miniBrasPinceExt4
    - miniBrasPinceExt4_boutDePince2
    - poussoirCentralPince_miniBrasPinceInt2
    - poussoirCentralPince_miniBrasPinceExt1
    - miniBrasPinceExt2_boutDePince1
    - chassis_roue1
    - chassis_roue2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: HIL_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_chassis_virtual_joint
      - chassis_bras1
      - chassis_bras2
      - bras2_moteur
      - moteur_poussoirCentralPince
      - poussoirCentralPince_miniBrasPinceInt2
      - poussoirCentralPince_miniBrasPinceExt1
      - miniBrasPinceExt2_boutDePince1
      - chassis_roue1
      - chassis_roue2